language: de_DE
libraries:
  - name: Movies
    lang:
      dub: de_DE
      sub: de_DE
    path: /**/movies/movies
  - name: Anime Movies
    lang:
      dub: de_DE
      sub: de_DE
    path: /**/movies/animes
  - name: TV Shows
    lang:
      dub: de_DE
      sub: de_DE
    path: /**/tvshows/tvshows
  - name: Anime TV Shows
    lang:
      dub: de_DE
      sub: de_DE
    path: /**/tvahows/animes
tvdb:
  api_key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  api_pin: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx