[tool.poetry]
name = "plexutils"
version = "1.0.0"
description = "tools for plex admins"
authors = ["Felix Rizzolli <felix.rizzolli@outlook.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
tvdb-v4-official = "^1.1.0"
pyyaml = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
