name: Unittests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
    - name: Install dependencies
      run: |
        poetry install
    - name: Run tests
      run: |
        poetry run python -m unittest tests/setup_testdata.py
        poetry run python -m unittest tests/shared/test_media.py
        poetry run python -m unittest tests/shared/test_menu.py
        poetry run python -m unittest tests/shared/test_plex_movie_crawler.py
        poetry run python -m unittest tests/shared/test_plex_tvshow_crawler.py
        poetry run python -m unittest tests/shared/test_utils_crawler.py